ng0: 
	npm install -g @angular/cli	
ng: 
	ng version
ng1: 
	ng new app30
ng1.1:
	cd app30 && npm install --save json-server
	cd app30 && mkdir server 
ng2:
	cd app30 && ng g c first
ng3:
	cd app30 && npm run generate
ng4:
	cd app30 && npm run serve
ng5:
	cd app30 && ng generate component home
ng6:
	cd app30 && ng generate component about
ng7:
	cd app30 && ng add @angular/material
ng8:
	cd app30 && ng generate service data
ng9:
	cd app30 && ng generate interface product 
